### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by dmarchewka**
I added 2 template sources. 

First one allows to reuse templates. Second one allows to use regular expressions to modify files.

### CODE REVIEW

**Comment by markround** [comment]
Wow, awesome! Thanks for this :)

**Comment by dmarchewka** [comment]
No problem, can you review my code? Any comments are welcome :-)

**Comment by markround** [comment]
Looks good. I'll have to add some documentation (do you happen to have any for your new plugins?) and fix a few of my existing tests now the log output has changed a little, but otherwise this is _awesome_ work. Thank you!

**Comment by dmarchewka** [comment]
I added some documentation for my plugins and created new pull request.

**Pull request merged**
