### PR TITLE
Continue rendering even if consul isn't available

### PR DESCRIPTION
**Pull request by oliverdrake**
Hi Mark,
First time writing ruby code, ran into an issue with the consul data source, I wanted to be able to test my docker image locally without consul running...
Background: we're planning to use consul in all our environments to override defaults defined inside tiller.
Use case: When developing a docker image, it's useful to be able to run your image locally without consul running, just to test that your dockerfile (and tiller) is mostly working.
Ideally this behaviour could be controlled by configuration and/or preferably by an environment variable.

### CODE REVIEW

**Comment by markround** [comment]
Nice one! Can you please make this pull against the `develop` branch ? I'll merge it and add a boolean config value to continue/abort on connection error. Thanks for the PR and suggestion!

**Comment by markround** [comment]
Thanks! I'll add a flag to control this behaviour and prepare a new release.

**Comment by markround** [comment]
Hmmm. Been thinking about this, and have just reverted it in my local branch for now - there's a few things I think could do with some more thought before I go ahead with this, and I'd value your input, to see if it's the best possible solution for your use-case.

Here's what I'm worried about: Normally, if Consul is down, I would assume that the correct thing to do would be for Tiller to bail out and refuse to generate configuration and start processes - otherwise, a network or infrastructure issue with your Consul cluster would lead to undefined and odd behaviour which could potentially lead to all kinds of problems, data-loss, etc. It seems that the safest thing to do in the event of Consul not being there is to shout loudly and stop.

Now, I get that you want to test your images without Consul running (although I'd say that ideally, your tests should provide a test Consul server - see [my tests](https://github.com/markround/tiller/blob/master/features/consul.feature) and some of the helpers [here](https://github.com/markround/tiller/tree/master/features/step_definitions) for an example using Aruba/Cucumber) , but this should not be the default option. So if we did this, we'd need a way of switching it on and off from the config file, e.g.

```yaml
consul:
  ignore_connection_error: true
```

Given that you'd really have to put that flag in your non-prod environments (so you'd have different configuration for your environments), would it not make more sense to have a `test` environment that simply didn't connect to Consul ? 

We could do this by moving the Consul configuration from the top-level, to only be in the environments you intend to use it in (like the production environment). This can already be done using the `common` block e.g.

```yaml
---
exec: ["cat","test.txt"]
data_sources: [ "file" , "consul"]
template_sources: [ "file" , "consul" ]

environments:

  production:
    common:
      consul:
        url: "http://127.0.0.1:8500"
        register_services: true
        register_nodes: true

  development:
    test.erb:
      target: test.txt
      config:
        test_var: "From file datasource"
```

Then, all we have to do is make it so that if there is no Consul config block defined, the consul plugin simply logs an informational message,  and doesn't try to retrieve any value.

What do you think? This seems to me to achieve your goal, clearly shows in the config files that you don't expect Consul to be there, and prevents some potentially dangerous behaviour.

**Comment by oliverdrake** [comment]
Yeh that sounds great, we had similar concerns for production/staging environments around the presence of consul. Just having the ability the pass in a different value for the `environment` env variable when running up an image locally without consul would fit my use case.

**Comment by markround** [comment]
https://github.com/markround/tiller/commit/142fb7824ca1629935a462d886f6ccc87ab655d9

Just put those changes into the `develop` branch. You should now be able to leave the consul block out for an environment, and you'll just get an informational message logged with `-v` verbosity.

**Pull request merged**
